server:
  port: 9000
spring:
  application:
    name: cards
  profiles:
    active: 'prod'
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  config:
    import: "optional:configserver:http://localhost:8071/"
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

# Enable the actuator to refresh the properties at runtime
management:
  endpoints:
    web:
      exposure:
        include: "*" # enable all available endpoints inside the actuator

# Backed up and no longer required
#  config:
#    import:
#      - 'application_qa.yml.backup'
#      - 'application_prod.yml.backup'
#    profiles:
#        active:
#          - "qa"
#
#
#build:
#  version: '3.0'
#
#cards:
#  message: "Welcome to CapferBank cards related local APIs"
#  contactDetails:
#    name: "Carlos Pereira - Developer"
#    email: "capfer27@gmail.com"
#  onCallSupport:
#    - (555) 555-1234
#    - (555) 523-1345