build:
  version: '2.0'
accounts:
  message: "Welcome to CapferBank account related QA APIs"
  contactDetails:
    name: "Jon Doe - QA Team Lead"
    email: "johndoe25@gmail.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371