server:
  port: 8090
spring:
  application:
    name: loans
  profiles:
    active: 'prod'
  datasource:
    url: jdbc:postgresql://localhost:5434/pg-loans-db
    username: postgres
    password: postgres
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password: ''
#  h2:
#    console:
#      enabled: true
  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none # We don't want to let hibernate create the database tables when the app starts
      open-in-view: false # changes how database sessions are handled in regard to open session in view pattern.
  sql:
    init:
      mode: always
    show-sql: true

  # Set up the url details of the config server
  config:
    import: "optional:configserver:http://localhost:8071/"
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

# Enable the actuator to refresh the properties at run time
management:
  endpoints:
    web:
      exposure:
        include: "*" # enable all available endpoints inside the actuator
#  health:
#    readiness-state:
#      enabled: true
#    liveness-state:
#      enabled: true

  endpoint:
    shutdown:
      #      enabled: true # this property is deprecated, therefore I use access: "unrestricted" instead
      access: "unrestricted" # to gracefully stops the accounts service
    health:
      probes:
        enabled: true # Automatically enables liveness and readiness states defined above in 'endpoints section'
  info:
    env:
      enabled: true

# This setup is no longer required. TODO: Remove it.
endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

# Useful information to display in eureka dashboard when multiple services are connected with it.
# It'll also be displayed as part of actuator info url.
info:
  app:
    name: "loans"
    description: "Capfer Bank Loans application"
    version: "1.0.0"

logging:
  level:
    com:
      capfer:
        loans: DEBUG

# Backed up and no longer required
#  config:
#    import:
#      - 'application_qa.yaml.backup'
#      - 'application_prod.yaml.backup'
#    profiles:
#      active:
#        - "qa"
#
#
#build:
#  version: '3.0'
#
#loans:
#  message: "Welcome to CapferBank loans related local APIs"
#  contactDetails:
#    name: "Carlos Pereira - Developer"
#    email: "capfer27@gmail.com"
#  onCallSupport:
#    - (555) 555-1234
#    - (555) 523-1345