build:
  version: '1.0'
loans:
  message: "Welcome to CapferBank loans related Production APIs"
  contactDetails:
    name: "Mestre Caito - Product Owner"
    email: "mestercaito25@gmail.com"
  onCallSupport:
    - (777) 562-4829
    - (777) 637-0384