build:
  version: '3.0'
loans:
  message: "Welcome to CapferBank loans related local APIs"
  contactDetails:
    name: "Carlos Pereira - Developer"
    email: "capfer27@gmail.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345