build:
  version: '2.0'
cards:
  message: "Welcome to CapferBank cards related Production APIs"
  contactDetails:
    name: "Mestre Caito - Product Owner"
    email: "mestercaito25@gmail.com"
  onCallSupport:
    - (777) 562-4829
    - (777) 637-0384