services:
  network-deploy-service:
    networks:
      - capferbank

  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m

  microservice-configserver-config:
    extends:
      service: microservice-base-config
#    depends_on: # Note: depends_on is no longer supported in new versions of spring boot.
#      config-server:
#        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8071/