spring:
 application:
  name: "configserver"
 profiles:
#   active: native # used only to access config files from classpath, locally and so on so forth
  active: git
 cloud:
   config:
#     enabled: true
     server:
#       native:
#         search-locations:
#          - "classpath:/config"
        git:
          uri: "https://github.com/capfer27/microservices-accounts-app-config.git"
          default-label: main # represents the default branch
          timeout: 5 # waits only for 5 seconds to connect, otherwise throw an exception
          clone-on-start: true # clone GitHub repo on start up
          force-pull: true

#   rabbitmq:
#     host: "localhost"
#     port: 5672
#     username: "guest"
#     password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*" # expose all endpoints including the monitor one: http://localhost:8071/monitor
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

# Tells Spring Cloud Config to encrypt my configurations while processing them
encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"
server:
  port: 8071
