spring:
 application:
  name: configserver
 profiles:
   active: native
 cloud:
   config:
#     enabled: true
     server:
       native:
         search-locations:
          - "classpath:/config"
#          - "classpath:/config/cards"
#          - "classpath:/config/loans"
server:
  port: 8071
