#server:
#  port: 8080
spring:
  application:
    name: "api-gateway-server"
  # Set up the url details of the config server
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false # enable the discovery locator to automatically route to services registered in eureka
              lower-case-service-id: true
#            x-forwarded:
#              for-enabled: true # to forward the original host and port details to the downstream services
#              proto-enabled: true

# Enable the actuator to refresh the properties at run time
management:
  endpoints:
    web:
      exposure:
        include: "*" # enable all available endpoints inside the actuator
  endpoint:
    gateway:
      # Use 'access' instead of 'enabled' for Spring Boot 4.x
      access: unrestricted
  info:
    env:
      enabled: true

# Useful information to display in eureka dashboard when multiple services are connected with it.
# It'll also be displayed as part of actuator info url.
info:
  app:
    name: "api-gateway-server"
    description: "Capfer Bank Gateway Server application"
    version: "1.0.0"

logging:
  level:
    com:
      capfer:
        apigatewayserver: DEBUG


